export interface VeterinariaUrgencia {
  id: string;
  nombre: string;
  comuna: string;
  region: 'ohiggins' | 'metropolitana';
  direccion: string;
  telefono: string;
  whatsapp?: string;
  atencion: '24 Horas' | 'Llamado Urgencia';
  observacion?: string;
  lat: number;
  lng: number;
}

export const VETERINARIAS_DATA: VeterinariaUrgencia[] = [
  // ==========================================
  // REGIÓN DE O'HIGGINS
  // ==========================================
  {
    id: 'vet-oh-1',
    nombre: 'Hospital Veterinario Rancagua (HVR)',
    comuna: 'Rancagua',
    region: 'ohiggins',
    direccion: 'Av. Libertador Bernardo O\'Higgins 01220',
    telefono: '+56722234000',
    whatsapp: '+56991234567',
    atencion: '24 Horas',
    observacion: 'Hospitalización, cirugía y urgencias críticas 24/7',
    lat: -34.1685,
    lng: -70.7420,
  },
  {
    id: 'vet-oh-2',
    nombre: 'Clínica Veterinaria Machalí Urgencias',
    comuna: 'Machalí',
    region: 'ohiggins',
    direccion: 'Av. San Juan 1450',
    telefono: '+56722891234',
    whatsapp: '+56988776655',
    atencion: '24 Horas',
    observacion: 'Pabellón, radiografía y urgencia médica permanente',
    lat: -34.1812,
    lng: -70.6654,
  },
  {
    id: 'vet-oh-3',
    nombre: 'Clínica Veterinaria Andes Rancagua',
    comuna: 'Rancagua',
    region: 'ohiggins',
    direccion: 'Av. Albert Einstein 290',
    telefono: '+56722258890',
    atencion: '24 Horas',
    observacion: 'Guardia médica continúa y exámenes inmediatos',
    lat: -34.1590,
    lng: -70.7305,
  },
  {
    id: 'vet-oh-4',
    nombre: 'Veterinaria Mostazal Central',
    comuna: 'Mostazal',
    region: 'ohiggins',
    direccion: 'Independencia 320',
    telefono: '+56977889900',
    whatsapp: '+56977889900',
    atencion: 'Llamado Urgencia',
    observacion: 'Atención nocturna con llamado previo',
    lat: -33.9922,
    lng: -70.7025,
  },
  {
    id: 'vet-oh-5',
    nombre: 'Clínica Veterinaria San Francisco',
    comuna: 'Mostazal',
    region: 'ohiggins',
    direccion: 'Av. Luco 145',
    telefono: '+56966554433',
    whatsapp: '+56966554433',
    atencion: 'Llamado Urgencia',
    observacion: 'Turno de retén y estabilización de emergencias',
    lat: -33.9905,
    lng: -70.7058,
  },
  {
    id: 'vet-oh-6',
    nombre: 'Clínica Veterinaria Graneros',
    comuna: 'Graneros',
    region: 'ohiggins',
    direccion: 'Av. La Compañía 412',
    telefono: '+56722471200',
    atencion: 'Llamado Urgencia',
    observacion: 'Atención de guardia para emergencias',
    lat: -34.0645,
    lng: -70.7258,
  },
  {
    id: 'vet-oh-7',
    nombre: 'Hospital Veterinario Colchagua',
    comuna: 'San Fernando',
    region: 'ohiggins',
    direccion: 'Av. Bernardo O\'Higgins 780',
    telefono: '+56722718900',
    whatsapp: '+56987654321',
    atencion: '24 Horas',
    observacion: 'Guardia veterinaria 24/7 y hospitalización',
    lat: -34.5841,
    lng: -70.9880,
  },
  {
    id: 'vet-oh-8',
    nombre: 'Clínica Veterinaria Rengo Sur',
    comuna: 'Rengo',
    region: 'ohiggins',
    direccion: 'Arturo Prat 450',
    telefono: '+56722511090',
    atencion: 'Llamado Urgencia',
    observacion: 'Retén nocturno y estabilización',
    lat: -34.4072,
    lng: -70.8601,
  },
  {
    id: 'vet-oh-9',
    nombre: 'Clínica Veterinaria Santa Cruz Urgencias',
    comuna: 'Santa Cruz',
    region: 'ohiggins',
    direccion: 'Av. Errázuriz 890',
    telefono: '+56722822100',
    atencion: '24 Horas',
    observacion: 'Atención médica permanente Colchagua',
    lat: -34.6385,
    lng: -71.3650,
  },

  // ==========================================
  // REGIÓN METROPOLITANA
  // ==========================================
  {
    id: 'vet-rm-1',
    nombre: 'Hospital Veterinario de Santiago (HVS)',
    comuna: 'Providencia',
    region: 'metropolitana',
    direccion: 'Av. Francisco Bilbao 2860',
    telefono: '+56222049444',
    whatsapp: '+56994441122',
    atencion: '24 Horas',
    observacion: 'UCI, traumatología, cirugía y urgencias 24 hrs',
    lat: -33.4389,
    lng: -70.6015,
  },
  {
    id: 'vet-rm-2',
    nombre: 'Clínica Veterinaria Las Condes 24h',
    comuna: 'Las Condes',
    region: 'metropolitana',
    direccion: 'Av. Las Condes 9820',
    telefono: '+56222208111',
    whatsapp: '+56988882233',
    atencion: '24 Horas',
    observacion: 'Laboratorio de urgencia, UCI y hospitalización',
    lat: -33.3820,
    lng: -70.5360,
  },
  {
    id: 'vet-rm-3',
    nombre: 'Hospital Veterinario Posta Animal',
    comuna: 'Ñuñoa',
    region: 'metropolitana',
    direccion: 'Av. Irarrázaval 3650',
    telefono: '+56222091234',
    whatsapp: '+56977773344',
    atencion: '24 Horas',
    observacion: 'Guardia presencial médica continua 24/7',
    lat: -33.4548,
    lng: -70.5982,
  },
  {
    id: 'vet-rm-4',
    nombre: 'Hospital Clínico Veterinario Maipú',
    comuna: 'Maipú',
    region: 'metropolitana',
    direccion: 'Av. Pajaritos 2200',
    telefono: '+56227415050',
    atencion: '24 Horas',
    observacion: 'Urgencias sector poniente con laboratorio propio',
    lat: -33.4985,
    lng: -70.7554,
  },
  {
    id: 'vet-rm-5',
    nombre: 'Clínica Veterinaria Alemana',
    comuna: 'Santiago Centro',
    region: 'metropolitana',
    direccion: 'Av. Portugal 652',
    telefono: '+56226343400',
    atencion: '24 Horas',
    observacion: 'Atención continua 24/7 centro de Santiago',
    lat: -33.4502,
    lng: -70.6385,
  },
  {
    id: 'vet-rm-6',
    nombre: 'Hospital Veterinario La Florida 24h',
    comuna: 'La Florida',
    region: 'metropolitana',
    direccion: 'Av. Vicuña Mackenna Poniente 6800',
    telefono: '+56222851200',
    whatsapp: '+56955554466',
    atencion: '24 Horas',
    observacion: 'Urgencias, ecografía y hospitalización',
    lat: -33.5180,
    lng: -70.5990,
  },
  {
    id: 'vet-rm-7',
    nombre: 'Hospital Veterinario Puente Alto',
    comuna: 'Puente Alto',
    region: 'metropolitana',
    direccion: 'Av. Concha y Toro 1820',
    telefono: '+56228509000',
    atencion: '24 Horas',
    observacion: 'Atención 24/7 zona cordillera y sur',
    lat: -33.6045,
    lng: -70.5780,
  },
  {
    id: 'vet-rm-8',
    nombre: 'Veterinaria Buin Sur Urgencias',
    comuna: 'Buin',
    region: 'metropolitana',
    direccion: 'Bernardo O\'Higgins 410',
    telefono: '+56228213344',
    atencion: 'Llamado Urgencia',
    observacion: 'Urgencias zona sur RM con llamado previo',
    lat: -33.7322,
    lng: -70.7385,
  },
  {
    id: 'vet-rm-9',
    nombre: 'Clínica Veterinaria San Bernardo 24h',
    comuna: 'San Bernardo',
    region: 'metropolitana',
    direccion: 'Eyzaguirre 890',
    telefono: '+56228591500',
    atencion: '24 Horas',
    observacion: 'Urgencias permanentes y hospital',
    lat: -33.5950,
    lng: -70.7020,
  },
  {
    id: 'vet-rm-10',
    nombre: 'Hospital Veterinario Peñalolén',
    comuna: 'Peñalolén',
    region: 'metropolitana',
    direccion: 'Av. Tobalaba 11500',
    telefono: '+56222794000',
    atencion: '24 Horas',
    observacion: 'Pabellón de urgencia y residencia médica continua',
    lat: -33.4880,
    lng: -70.5390,
  }
];
